"""
Anderson University — Degree Audit Web App
Indy Collab, LLC
"""

import os, io, csv, json, hashlib, datetime, tempfile, importlib.util, smtplib
from email.message import EmailMessage
from pathlib import Path
from fastapi import FastAPI, UploadFile, File, Form, HTTPException, Depends, Request
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.security import HTTPBasic, HTTPBasicCredentials
import secrets

# ── CONFIG ────────────────────────────────────────────────────────────────────
APP_PASSWORD = os.environ.get("AUDIT_PASSWORD", "ravens2025")   # change in prod
LOG_FILE     = Path("logs/audit_log.json")
ENGINES_DIR  = Path("engines")
MAX_PULLS    = int(os.environ.get("MAX_PULLS", 1000))

MAJORS = {
    "management":     {"label": "Management",     "engine": "management"},
    "sport_marketing": {"label": "Sport Marketing", "engine": "sport_marketing"},
}

CATALOG_YEARS = ["2022-23", "2023-24", "2024-25", "2025-26"]

# ── EMAIL ─────────────────────────────────────────────────────────────────────
GMAIL_USER = os.environ.get("GMAIL_USER", "")
GMAIL_PASS = os.environ.get("GMAIL_PASS", "")

def send_audit_email(to_addresses: list[str], student_name: str, major_label: str,
                     pdf_path: str, filename: str):
    """Send the audit PDF to one or more addresses via Gmail SMTP."""
    if not GMAIL_USER or not GMAIL_PASS:
        raise RuntimeError("Email credentials not configured (GMAIL_USER / GMAIL_PASS env vars missing).")
    if not to_addresses:
        return

    msg = EmailMessage()
    msg['Subject'] = f"Degree Audit — {student_name} — {major_label}"
    msg['From']    = f"Selah Academic Solutions <{GMAIL_USER}>"
    msg['To']      = ", ".join(to_addresses)
    msg.set_content(
        f"Please find attached the degree completion audit for {student_name} ({major_label}).\n\n"
        f"This audit was generated by the Selah Academic Solutions degree audit system on behalf of "
        f"Anderson University. Please verify all requirements with your academic advisor.\n\n"
        f"— Selah Academic Solutions\n"
        f"  audit.selahacademic.com"
    )

    with open(pdf_path, 'rb') as f:
        msg.add_attachment(f.read(), maintype='application', subtype='pdf', filename=filename)

    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        smtp.login(GMAIL_USER, GMAIL_PASS)
        smtp.send_message(msg)

# ── APP ───────────────────────────────────────────────────────────────────────
app = FastAPI(title="AU Degree Audit", docs_url="/docs", redoc_url=None)
security = HTTPBasic()

# ── ROUTER (all majors, minors, liberal arts) ─────────────────────────────────
from engines.audit_routes import router
app.include_router(router)

# ── AUTH ──────────────────────────────────────────────────────────────────────
def verify(credentials: HTTPBasicCredentials = Depends(security)):
    ok = secrets.compare_digest(credentials.password.encode(), APP_PASSWORD.encode())
    if not ok:
        raise HTTPException(status_code=401, detail="Unauthorized",
                            headers={"WWW-Authenticate": "Basic"})
    return credentials.username

# ── LOGGING ───────────────────────────────────────────────────────────────────
def load_log():
    if LOG_FILE.exists():
        return json.loads(LOG_FILE.read_text())
    return {"pulls": [], "total": 0}

def save_log(log):
    LOG_FILE.parent.mkdir(exist_ok=True)
    LOG_FILE.write_text(json.dumps(log, indent=2))

def record_pull(user, student, major, catalog):
    log = load_log()
    log["pulls"].append({
        "ts":      datetime.datetime.utcnow().isoformat(),
        "user":    user,
        "student": student,
        "major":   major,
        "catalog": catalog,
    })
    log["total"] = len(log["pulls"])
    save_log(log)
    return log["total"]

# ── ENGINE LOADER ─────────────────────────────────────────────────────────────
def load_engine(major_key: str):
    engine_file = ENGINES_DIR / f"{MAJORS[major_key]['engine']}.py"
    if not engine_file.exists():
        raise HTTPException(status_code=400, detail=f"Engine not found for {major_key}")
    spec = importlib.util.spec_from_file_location("engine", engine_file)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

# ── ROUTES ────────────────────────────────────────────────────────────────────
@app.get("/", response_class=HTMLResponse)
def index(request: Request):
    return HTMLResponse(open("templates/index.html").read())

@app.get("/dashboard", response_class=HTMLResponse)
def dashboard(user=Depends(verify)):
    log  = load_log()
    html = open("templates/dashboard.html").read()
    pulls_remaining = MAX_PULLS - log["total"]
    recent = log["pulls"][-10:][::-1]
    rows = "".join(
        f'<tr><td>{p["ts"][:16].replace("T"," ")}</td>'
        f'<td>{p.get("student","—")}</td>'
        f'<td>{p.get("major","—")}</td>'
        f'<td>{p.get("catalog","—")}</td></tr>'
        for p in recent
    )
    html = html.replace("{{TOTAL}}", str(log["total"]))
    html = html.replace("{{REMAINING}}", str(max(0, pulls_remaining)))
    html = html.replace("{{MAX}}", str(MAX_PULLS))
    html = html.replace("{{ROWS}}", rows or "<tr><td colspan='4'>No audits yet</td></tr>")
    pct = min(100, round(log["total"] / MAX_PULLS * 100))
    html = html.replace("{{PCT}}", str(pct))
    return HTMLResponse(html)

@app.post("/generate")
async def generate(
    student_name:  str = Form(...),
    major:         str = Form(...),
    catalog_year:  str = Form(...),
    transcript:    UploadFile = File(...),
    exceptions:    str = Form(""),
    minor1:        str = Form(""),
    advisor_email: str = Form(""),
    student_email: str = Form(""),
):
    if major not in MAJORS:
        raise HTTPException(400, "Invalid major")
    if catalog_year not in CATALOG_YEARS:
        raise HTTPException(400, "Invalid catalog year")

    log = load_log()
    if log["total"] >= MAX_PULLS:
        raise HTTPException(429, "Annual pull limit reached. Contact Indy Collab to renew.")

    csv_bytes = await transcript.read()
    with tempfile.NamedTemporaryFile(suffix=".csv", delete=False, mode="wb") as tmp_in:
        tmp_in.write(csv_bytes)
        tmp_csv = tmp_in.name

    safe_name = "".join(c if c.isalnum() or c in "_ " else "_" for c in student_name).strip()
    tmp_pdf = tempfile.mktemp(suffix=".pdf")

    try:
        mod = load_engine(major)
        courses = mod.parse_csv(tmp_csv)
        # Apply advisor exceptions before audit
        if exceptions.strip() and hasattr(mod, 'apply_exceptions'):
            courses = mod.apply_exceptions(courses, exceptions)
        res     = mod.audit(courses, minor_key=minor1 or None)
        major_label = MAJORS[major]["label"]
        mod.build(res, student_name, major_label, tmp_pdf, exceptions=exceptions)

        if hasattr(mod, 'set_catalog_year'):
            mod.set_catalog_year(catalog_year)
            mod.build(res, student_name, major_label, tmp_pdf, exceptions=exceptions)

        total = record_pull("advisor", student_name, MAJORS[major]["label"], catalog_year)

        filename = f"{safe_name}_{major_label.replace(' ','_')}_Audit.pdf"

        # Send email if addresses provided
        recipients = [e.strip() for e in [advisor_email, student_email] if e.strip()]
        if recipients:
            try:
                send_audit_email(recipients, student_name, major_label, tmp_pdf, filename)
            except Exception as email_err:
                # Don't fail the whole request if email fails — PDF still downloads
                print(f"Email send failed: {email_err}")

        return FileResponse(
            tmp_pdf,
            media_type="application/pdf",
            filename=filename,
            headers={"X-Pulls-Used": str(total), "X-Pulls-Remaining": str(MAX_PULLS - total)}
        )
    except Exception as e:
        raise HTTPException(500, f"Audit generation failed: {str(e)}")
    finally:
        os.unlink(tmp_csv)



@app.post("/generate/non-fsb")
async def generate_non_fsb(
    student_name:  str = Form(...),
    major:         str = Form(...),
    catalog_year:  str = Form(...),
    transcript:    UploadFile = File(...),
    exceptions:    str = Form(""),
    minor1:        str = Form(""),
    advisor_email: str = Form(""),
    student_email: str = Form(""),
):
    if catalog_year not in CATALOG_YEARS:
        raise HTTPException(400, "Invalid catalog year")

    log = load_log()
    if log["total"] >= MAX_PULLS:
        raise HTTPException(429, "Annual pull limit reached. Contact Indy Collab to renew.")

    csv_bytes = await transcript.read()
    with tempfile.NamedTemporaryFile(suffix=".csv", delete=False, mode="wb") as tmp_in:
        tmp_in.write(csv_bytes)
        tmp_csv = tmp_in.name

    safe_name = "".join(c if c.isalnum() or c in "_ " else "_" for c in student_name).strip()
    tmp_pdf = tempfile.mktemp(suffix=".pdf")

    try:
        # Parse CSV using shared parser
        sm_mod = load_engine("sport_marketing")
        raw_courses = sm_mod.parse_csv(tmp_csv)

        # Build the sport_marketing-compatible res dict for non-FSB majors
        from engines.non_fsb_audit_engine import run_non_fsb_audit, CourseRecord as NonFSBCourseRecord
        from requirements.non_fsb_programs import get_non_fsb_requirements

        transcript_records = [
            NonFSBCourseRecord(
                course_id=c["raw"],
                grade=c["grade"],
                credits=c["cr"],
                term=c.get("reg_date", ""),
            )
            for c in raw_courses
        ]

        student = {"name": student_name, "id": "", "catalog_year": catalog_year}
        non_fsb_result = run_non_fsb_audit(
            program_key=major,
            catalog_year=catalog_year,
            student=student,
            transcript=transcript_records,
        )

        # Convert NonFSBAuditResult → res dict shaped for the shared PDF template
        def _status(s):
            return "Not Satisfied" if s == "Not Met" else s

        mr_rows = [
            {
                "id": r.label.replace(" ", "_").upper()[:20],
                "label": r.label,
                "status": _status(r.status),
                "course": {"raw": r.course_used, "name": "", "cr": 0,
                           "grade": "", "status": "grade posted", "reg_date": ""}
                          if r.course_used else None,
                "dcr": 3,
                "note": r.notes or "",
            }
            for r in non_fsb_result.requirements
        ]

        # Compute simple GPA/credit stats from raw_courses
        gpa_courses = [c for c in raw_courses if c["grade"].upper() not in ("", "T", "W", "DRP", "NC", "IP", "CR/IP")]
        gpa_hrs = sum(c["cr"] for c in gpa_courses if c["status"] == "grade posted")
        gp_map = {"A":4.0,"A-":3.7,"B+":3.3,"B":3.0,"B-":2.7,"C+":2.3,"C":2.0,
                  "C-":1.7,"D+":1.3,"D":1.0,"D-":0.7,"F":0.0}
        qp = sum(c["cr"] * gp_map.get(c["grade"].upper(), 0.0)
                 for c in gpa_courses if c["status"] == "grade posted")
        gpa_o = round(qp / gpa_hrs, 2) if gpa_hrs > 0 else 0.0
        earned = sum(c["cr"] for c in raw_courses
                     if c["status"] == "grade posted" and c["grade"].upper() not in ("","W","DRP","NC","F"))
        ip_hrs = sum(c["cr"] for c in raw_courses if c["status"] == "current")
        sched_hrs = sum(c["cr"] for c in raw_courses if c["status"] == "scheduled")
        proj = earned + ip_hrs + sched_hrs

        # Get program display name
        prog_reqs = get_non_fsb_requirements(major, catalog_year) or {}
        prog_name = prog_reqs.get("name", major.replace("_", " ").title()) if isinstance(prog_reqs, dict) else major.replace("_", " ").title()

        res = {
            "catalog_year": catalog_year,
            "current_term_label": "2025-26",
            "gpa_o": gpa_o,
            "gpa_m": round(non_fsb_result.major_gpa, 2),
            "earned": earned,
            "ip_hrs": ip_hrs,
            "proj": proj,
            "gpa_hrs": gpa_hrs,
            "qp": round(qp, 1),
            # LA section — empty for non-FSB (LA is universal, not major-specific)
            "la": [],
            # No business core for non-FSB
            "bc": [],
            # Major requirements
            "mr": mr_rows,
            # No electives section for non-FSB
            "elecs": [],
            "elecs_ip": [],
            "ehrs": 0,
            "ehrs_ip": 0,
            "elec_required_hrs": 0,
            # Course history
            "courses": raw_courses,
            # Minor
            "minor_rows": None,
            "minor_key": None,
            # Template labels
            "major_section_label": f"{prog_name} — {catalog_year}",
            "major_subsections": [(f"{prog_name} Required Courses", mr_rows)],
            "notes_row_text": "",
            "elec_opts": [],
        }

        sm_mod.build(res, student_name, prog_name, tmp_pdf, exceptions=exceptions)

        total = record_pull("advisor", student_name, major, catalog_year)
        filename = f"{safe_name}_{major.replace('_', ' ').title()}_Audit.pdf"

        recipients = [e.strip() for e in [advisor_email, student_email] if e.strip()]
        if recipients:
            try:
                send_audit_email(recipients, student_name, major, tmp_pdf, filename)
            except Exception as email_err:
                print(f"Email send failed: {email_err}")

        return FileResponse(
            tmp_pdf,
            media_type="application/pdf",
            filename=filename,
            headers={"X-Pulls-Used": str(total), "X-Pulls-Remaining": str(MAX_PULLS - total)}
        )
    except Exception as e:
        raise HTTPException(500, f"Audit generation failed: {str(e)}")
    finally:
        os.unlink(tmp_csv)

@app.get("/ping")
def ping():
    return {"ok": True}

@app.get("/status")
def status():
    log = load_log()
    return {
        "total_pulls":     log["total"],
        "remaining_pulls": max(0, MAX_PULLS - log["total"]),
        "max_pulls":       MAX_PULLS,
        "majors_available": [v["label"] for v in MAJORS.values()],
        "catalog_years":   CATALOG_YEARS,
    }
